export type EventType =
  // --- PAYMENTS (Transaction Lifecycle) ---
  | "PAYMENT_CREATED"
  | "PAYMENT_SUCCEEDED"
  | "PAYMENT_FAILED"
  | "PAYMENT_PROCESSING"
  | "PAYMENT_CANCELED"
  | "PAYMENT_AUTHORIZED" // Funds held (Auth)
  | "PAYMENT_CAPTURED" // Funds captured

  // --- REFUNDS & DISPUTES ---
  | "REFUND_CREATED"
  | "REFUND_PROCESSED"
  | "REFUND_FAILED"
  | "DISPUTE_CREATED"
  | "DISPUTE_RESOLVED"
  | "DISPUTE_EXPIRED" // Merchant failed to provide evidence in time

  // --- CHECKOUT ---
  | "CHECKOUT_COMPLETED"
  | "CHECKOUT_EXPIRED"

  // --- SUBSCRIPTIONS (Lifecycle) ---
  | "SUBSCRIPTION_CREATED"
  | "SUBSCRIPTION_UPDATED"
  | "SUBSCRIPTION_CANCELED"
  | "SUBSCRIPTION_PAUSED"
  | "SUBSCRIPTION_RESUMED"
  | "SUBSCRIPTION_TRIAL_WILL_END"
  | "SUBSCRIPTION_EXPIRING"
  | "SUBSCRIPTION_PAYMENT_FAILED" // Recurring invoice payment specifically failed

  // --- INVOICES (Recurring Billing Specific) ---
  | "INVOICE_PAYMENT_SUCCEEDED"
  | "INVOICE_PAYMENT_FAILED"

  // --- CUSTOMERS ---
  | "CUSTOMER_CREATED"
  | "CUSTOMER_UPDATED"
  | "CUSTOMER_DELETED"

  // --- PAYMENT METHODS ---
  | "PAYMENT_METHOD_ATTACHED"
  | "PAYMENT_METHOD_DETACHED"
  | "MANDATE_CREATED";

/**
 * Represents a normalized, provider-agnostic event within the Revstack ecosystem.
 * * This interface acts as the "Universal Translator" between different payment
 * gateways (Stripe, Polar, PayPal) and the Revstack Cloud, ensuring that the
 * business logic remains decoupled from provider-specific implementation details.
 */
export interface RevstackEvent {
  /**
   * The normalized event category (e.g., 'PAYMENT_SUCCEEDED', 'SUBSCRIPTION_CANCELED').
   * Used by the Cloud orchestrator to route business logic.
   */
  type: EventType;

  /**
   * The unique identifier assigned to this specific event instance by the provider.
   * Crucial for idempotency checks to prevent processing the same event multiple times.
   */
  providerEventId: string;

  /**
   * The timestamp when the event was originally generated by the provider.
   */
  createdAt: Date;

  /**
   * The primary identifier of the underlying resource affected by this event.
   * - For payments: typically the Payment Intent ID (pi_...)
   * - For subscriptions: the Subscription ID (sub_...)
   * This ID should be usable in 'getPayment' or 'getSubscription' methods.
   */
  resourceId: string;

  /**
   * The provider-specific customer identifier (e.g., 'cus_...').
   * Helps in quickly mapping the event to a specific account in the provider's dashboard.
   */
  customerId?: string;

  /**
   * The internal Revstack identifier (e.g., User ID or Workspace ID) provided
   * during the creation of the resource.
   * * This is the "Golden Thread" for database reconciliation: it allows the Cloud
   * to immediately identify which local entity owns the event without extra API lookups.
   */
  clientReferenceId?: string;

  /**
   * A flexible dictionary for normalized or injected metadata.
   * * Should contain:
   * 1. Business-level metadata passed during resource creation (e.g., plan_id).
   * 2. Provider-specific hints (e.g., { stripeType: 'checkout.session.completed' }).
   * 3. Tracing information (e.g., { revstack_trace_id: '...' }).
   */
  metadata?: Record<string, any>;

  /**
   * The complete, unaltered raw payload received from the provider's webhook.
   * Primarily used for deep debugging or extracting non-standard fields that
   * are not yet part of the normalized Revstack contract.
   */
  originalPayload: any;
}

export interface WebhookResponse {
  statusCode: number;
  body: any;
}
