/**
 * src/types/models.ts
 * * Normalized data models for the Revstack ecosystem.
 * These types represent the "Internal Source of Truth" for the OS.
 */

// =============================================================================
// PAYMENT MODELS
// =============================================================================

export enum PaymentStatus {
  Pending = "pending",
  Authorized = "authorized", // Funds held but not captured
  Succeeded = "succeeded",
  Failed = "failed",
  Refunded = "refunded",
  PartiallyRefunded = "partially_refunded",
  Disputed = "disputed",
  Canceled = "canceled",
}

export type PaymentMethodDetails = {
  type: "card" | "bank_transfer" | "wallet" | "crypto" | "checkout";
  brand?: string; // e.g., 'visa', 'mastercard'
  last4?: string; // e.g., '4242'
  email?: string; // e.g., paypal email
};

export type Payment = {
  /** Unique ID in Revstack (UUID) */
  id: string;
  /** The slug of the provider (e.g., 'stripe') */
  providerId: string;
  /** The ID generated by the provider (e.g., 'pi_12345') */
  externalId: string;

  /** Total amount in lowest currency unit (e.g., cents) */
  amount: number;
  /** Amount refunded so far */
  amountRefunded: number;
  /** ISO 4217 Currency Code (e.g., 'USD') */
  currency: string;

  status: PaymentStatus;
  method?: PaymentMethodDetails;

  description?: string;

  /** Revstack internal Customer ID */
  customerId?: string;
  /** Provider-specific Customer ID (e.g., 'cus_999') */
  externalCustomerId?: string;

  /** * The fee charged by the provider for this transaction.
   * Crucial for Net Revenue calculations.
   */
  fee?: number;

  /** ISO Date String */
  createdAt: string;
  /** ISO Date String */
  updatedAt?: string;

  metadata?: Record<string, any>;
  /** Optional: The raw object from the provider for debugging/audit */
  raw?: any;
};

// =============================================================================
// SUBSCRIPTION MODELS
// =============================================================================

export enum SubscriptionStatus {
  Trialing = "trialing",
  Active = "active",
  PastDue = "past_due", // Payment failed, in grace period
  Canceled = "canceled",
  Unpaid = "unpaid", // Grace period ended, service cut
  Incomplete = "incomplete", // Created but waiting for first payment (3DS)
  IncompleteExpired = "incomplete_expired",
  Paused = "paused",
}

export type SubscriptionInterval = "day" | "week" | "month" | "year";

export type Subscription = {
  id: string;
  providerId: string;
  externalId: string;

  status: SubscriptionStatus;

  // -- Pricing --
  /** Internal Plan ID */
  planId?: string;
  /** Provider Plan/Price ID (e.g., 'price_Hk123') */
  externalPlanId?: string;
  amount: number;
  currency: string;
  interval: SubscriptionInterval;

  customerId: string;

  // -- Billing Cycle Logic --
  /** Start of the current billing period (ISO Date) */
  currentPeriodStart: string;
  /** End of the current billing period (ISO Date) */
  currentPeriodEnd: string;

  /** If true, the subscription will cancel at the end of the current period */
  cancelAtPeriodEnd: boolean;
  canceledAt?: string;

  startedAt: string;
  endedAt?: string;
  trialStart?: string;
  trialEnd?: string;

  metadata?: Record<string, any>;
};

// =============================================================================
// INPUT / OUTPUT TYPES FOR FEATURES
// =============================================================================

export type CreatePaymentInput = {
  amount: number;
  currency: string;
  customerId?: string; // If known
  paymentMethodId?: string; // If reusing a saved method
  description?: string;
  metadata?: Record<string, any>;
  /** Pass-through options for the specific provider */
  providerOptions?: any;
};

export type PaymentResult = {
  payment: Payment;
  /** If the payment requires 3DS or redirect */
  nextAction?: {
    type: "redirect" | "modal";
    url: string;
  };
};

export type CreateSubscriptionInput = {
  customerId: string; // Must exist in provider
  planId?: string; // Internal Plan ID
  priceId?: string; // Provider Price ID (preferred for Stripe)
  amount?: number; // Custom amount (if supported)
  currency?: string;
  trialDays?: number;
  metadata?: Record<string, any>;
};

export type SubscriptionResult = {
  subscription: Subscription;
};

export type CheckoutSessionInput = {
  customerId?: string;
  /** Items to purchase */
  lineItems: {
    name: string;
    amount: number;
    quantity: number;
    currency: string;
    images?: string[];
  }[];
  successUrl: string;
  cancelUrl: string;
  mode: "payment" | "subscription";
  metadata?: Record<string, any>;
};

export type CheckoutSessionResult = {
  id: string;
  url: string;
  expiresAt?: string;
};
