import {
  BaseProvider,
  CheckoutSessionInput,
  CheckoutSessionResult,
  CreatePaymentInput,
  CreateSubscriptionInput,
  InstallInput,
  InstallResult,
  PaymentResult,
  ProviderCategory,
  ProviderContext,
  ProviderManifest,
  RevstackEvent,
  SubscriptionResult,
  WebhookResponse,
} from "@revstackhq/providers-core";

export const manifest: ProviderManifest = {
  name: "Stripe",
  slug: "stripe",
  version: "1.0.0",
  logoUrl:
    "https://cdn.jsdelivr.net/npm/@revstackhq/provider-stripe/assets/logo.svg",
  category: ProviderCategory.Card,
  capabilities: {
    checkout: {
      supported: true,
      strategy: "redirect",
    },
    payments: {
      supported: true,
      features: {
        capture: false,
        disputes: true,
        partialRefunds: true,
        refunds: true,
      },
    },
    subscriptions: {
      supported: true,
      mode: "native",
      features: {
        cancellation: true,
        pause: true,
        resume: true,
        proration: true,
      },
    },
    webhooks: {
      supported: true,
      verification: "signature",
    },
  },
  author: "Revstack",
  currencies: ["USD"],
  description:
    "Stripe is a payment processing platform that enables businesses to accept payments online. It provides a secure and convenient way for customers to pay for goods or services using various payment methods, including credit cards, bank transfers, and digital wallets.",
  documentationUrl: "https://docs.revstack.dev/providers/stripe",
  regions: ["*"],
  sandboxAvailable: true,
  supportUrl: "https://docs.revstack.dev/providers/stripe#support",
  configSchema: {
    apiKey: {
      label: "Secret Key",
      type: "password",
      secure: true,
      required: true,
    },
    webhookSecret: {
      label: "Webhook Signing Secret",
      type: "password",
      secure: true,
      required: false,
      description:
        "Fill this if you have configured a custom webhook secret. Otherwise, it will be autogenerated.",
    },
  },
};

export class StripeProvider extends BaseProvider {
  static manifest = manifest;
  manifest = manifest;

  onInstall(ctx: ProviderContext, input: InstallInput): Promise<InstallResult> {
    console.log(input.webhookUrl);
    throw new Error("Method not implemented.");
  }

  verifyWebhookSignature(
    payload: string | Buffer,
    headers: Record<string, string | string[] | undefined>,
    secret: string,
  ): Promise<boolean> {
    throw new Error("Method not implemented.");
  }

  parseWebhookEvent(payload: any): Promise<RevstackEvent | null> {
    throw new Error("Method not implemented.");
  }

  getWebhookResponse(): Promise<WebhookResponse> {
    throw new Error("Method not implemented.");
  }

  createPayment(
    ctx: ProviderContext,
    input: CreatePaymentInput,
  ): Promise<PaymentResult> {
    throw new Error("Method not implemented.");
  }

  getPayment(ctx: ProviderContext, id: string): Promise<PaymentResult> {
    throw new Error("Method not implemented.");
  }

  createSubscription(
    ctx: ProviderContext,
    input: CreateSubscriptionInput,
  ): Promise<SubscriptionResult> {
    throw new Error("Method not implemented.");
  }

  cancelSubscription(
    ctx: ProviderContext,
    id: string,
    reason?: string,
  ): Promise<SubscriptionResult> {
    throw new Error("Method not implemented.");
  }

  pauseSubscription(
    ctx: ProviderContext,
    id: string,
    reason?: string,
  ): Promise<SubscriptionResult> {
    throw new Error("Method not implemented.");
  }

  resumeSubscription(
    ctx: ProviderContext,
    id: string,
    reason?: string,
  ): Promise<SubscriptionResult> {
    throw new Error("Method not implemented.");
  }

  createCheckoutSession(
    ctx: ProviderContext,
    input: CheckoutSessionInput,
  ): Promise<CheckoutSessionResult> {
    throw new Error("Method not implemented.");
  }
}

export default {
  manifest,
  StripeProvider,
};
